Eslint + prettier + daisyUI
BaDo2001/localization-framework pull request #15
Opened 2023-10-21 10:49 UTC by BaDo2001

2023-11-01 13:40 UTC, tothpeterdev requested changes
A line ending-eket be kellene állítani, hogy konzisztensek legyenek, most _Delete `CR` eslint(prettier/prettier)_ error-okat dob az ESLint

2023-11-01 21:04 UTC, BaDo2001 commented
https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings?platform=windows

Be van állítva az autocrlf?

2023-11-01 22:08 UTC, tothpeterdev commented on admin-site/.eslintrc.json
> +    "prettier/prettier": "error",
```suggestion
    "prettier/prettier": ["error", { "endOfLine": "auto" }],
```

2023-11-01 22:12 UTC, tothpeterdev commented on admin-site/.eslintrc.json
> +    "prettier/prettier": "error",
Windows-on az autocrlf alapból be van állítva, szóval ez kezeli az EOL konvertálásokat, így elég az ESLint config-ot átírni

2023-11-01 22:24 UTC, tothpeterdev requested changes
Windows-on az autocrlf alapból be van állítva, szóval ez kezeli az EOL konvertálásokat, így elég az ESLint config-ot átírni, hogy az OS EOL-jét használja

2023-11-03 18:32 UTC, tothpeterdev approved these changes

2023-11-03 19:13 UTC, merged